### ISSUE TITLE
Logging with ain2 broken

### ISSUE THREAD

**Issue by lephyrus** [publicmediaplatform/metalogger#10]
We use `metalogger` with the following configuration:
```
NODE_LOGGER_LEVEL=info
NODE_LOGGER_GRANULARLEVELS=0
NODE_LOGGER_PLUGIN=ain2
NODE_LOGGER_SYSLOG_FACILITY=local0
NODE_LOGGER_SYSLOG_APPNAME=<app-name>
```
Since v1.1.0, the resulting log file looks like this:
```
Jan 19 14:30:42 INFO  [var/www/.../app.js:66]  'info'
Jan 19 14:30:42 ERR  [var/www/.../app.js:51]  'info'
Jan 19 14:30:42 INFO  [var/www/...app.js:66]  'info'
Jan 19 14:30:42 INFO  [var/www/.../app.js:66]  'info'
Jan 19 14:30:42 ERR  [var/www/.../app.js:51]  'info'
```
The actual message is always `'info'` (which is not the message's log level, either). Reverting to v1.0.1 restores correct functionality, but a fix would be appreciated.

Great work with this library, by the way - `metalogger` is very helpful to manage logging across development and production.

**Comment by inadarei** [comment]
Thanks a lot for the report. We will look into it right away and get back to you.

**Comment by inadarei** [comment]
@lephyrus, @randallsquared fixed it in 1.2.2. Should be published to NPM. Can you please try and let us know?

Thanks,

Irakli

**Comment by lephyrus** [comment]
@inadarei With v1.2.2, everything works as expected again. Thanks a lot for the quick fix!

**Comment by inadarei** [comment]
That's great to hear. Thank you!
