### ISSUE TITLE
🎶 Loggly bridge is falling down 🎶

### ISSUE THREAD

**Issue by maxwerr** [publicmediaplatform/metalogger#13]
Auth token isn't passed into the loggly client in [lib/bridges/loggly.js](https://github.com/publicmediaplatform/metalogger/blob/master/lib/bridges/loggly.js). I opened [https://github.com/publicmediaplatform/metalogger/pull/12](https://github.com/publicmediaplatform/metalogger/pull/12) several days ago to fix this. Please let me know if I can help in another way.

**Comment by inadarei** [comment]
@maxwerr have you tested your pull request? I don't think it works. You moved authToken under options object, but the check on line 113 was left at its original `if(authToken) {` and given how authToken will always be null, I don't see how it can work.

**Comment by inadarei** [comment]
OK, I just tested that your PR doesn't work. There're number of issues, but what I am going to do is: accept this and then fix whatever else needs fixing.

**Comment by inadarei** [comment]
Fixed in v 1.3.0

**Comment by maxwerr** [comment]
Thank you, I was hoping to get feedback from contributors before spending more time on it in case I was chasing the wrong rabbit altogether. Thanks for fixing the issue!

**Comment by inadarei** [comment]
Thank you
